# Generated by Django 3.1.1 on 2020-10-13 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20200709_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 12, 4, 50, 786855)),
        ),
    ]
