# Generated by Django 3.2.5 on 2021-07-09 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20201013_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 12, 24, 5, 854766)),
        ),
    ]
